accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register_one, name='register_one'),
    path('register/photoappuser/', views.SignUp.as_view(), name='register'),
    path('members/', views.member_list_view, name='member_list'),
    path('register/updatepwd/', views.update_pwd, name='update_pwd'),
]

photoapp/urls.py
from django.urls import path
from .views import (
    photo_list_view,
    photo_detail_view,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    delete_comment,
    about_view,
    edit_comment,
    recent_activity,
)

app_name = 'photo'

urlpatterns = [
    path('', photo_list_view, name='list'),
    path('<int:pk>/', photo_detail_view, name='detail'),
    path('create/', PhotoCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
    path('<int:pk>/delete_comment/', delete_comment, name='delete_comment'),
    path('about/', about_view, name='about'),
    path('comment/<int:pk>/edit/', edit_comment, name='edit_comment'),
    path('activity/', recent_activity, name='activity'),
]

photosmith/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import MyLoginView
from django.http import JsonResponse, HttpResponseNotFound
from django.views.decorators.csrf import ensure_csrf_cookie
from django.middleware.csrf import get_token


@ensure_csrf_cookie
def csrf_probe(request):
    if not settings.DEBUG:
        return HttpResponseNotFound()
    token = get_token(request)  # forces a token to exist
    return JsonResponse({
        "has_cookie": "csrftoken" in request.COOKIES,
        "cookie_len": len(request.COOKIES.get("csrftoken", "")),
        "token_len": len(token),
        "host": request.get_host(),
        "secure": request.is_secure(),
    })


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MyLoginView.as_view(), name='login'),
    path('photo/', include('photoapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [ path("_csrfprobe/", csrf_probe) ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>TeamUsPhoto:{{ message }}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/photosmith.css' %}">
  </head>
  <body style="background-color:#000023">
    {% include 'navbar.html' %}

    <div class="container mt-4">
    {% block body %}

    {% endblock body %}

    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
    <div class="container">
      <div class="d-flex align-items-center justify-content-center" style="height: 350px">
      <form method="POST">
        {% csrf_token %}
        <div class="text-dark">
          Email Address:
        </div>
        <input class="form-control" type="text" name="username" autofocus=""
        autocapitalize="none" autocomplete="username" maxlength="255" required=""
        id="id_username">
        <div class="text-dark mt-3">
          Password:
        </div>
        <input class="form-control" type="password" name="password" autocomplete=
        "current-password" required="" id="id_password">
        <div class="mt-4 text-center">
          <input type="submit" class="btn btn-dark" value="Log in">
        </div>
      </form>
      </div>
    </div>
{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-warning fw-bold" href="{% url 'photo:list' %}?page=1">TeamUsPhoto
    <img src="/media/logo.png" alt="Logo"></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse flex-row-reverse"
      id="navbarTogglerDemo02"
    >
    {% if user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li class="nav-item me-2">
          <a class="nav-link active text-warning" href="{% url 'photo:list' %}?page=1" style="background:none !important">
            <img src="/media/home.webp" alt="Home">
          </a>
        </li>
        {% if user.is_editor %}
        <li class="nav-item me-3">
          <a class="nav-link active text-warning" href="{% url 'photo:create' %}" style="background:none !important">
            <img src="/media/addicon.png" alt="Add Photo">
          </a>
        </li>
        {% endif %}
        <li class="nav-item me-3">
          <form class="form-inline" method="GET" action="{% url 'photo:list' %}">
            {% csrf_token %}
            <input class="form-control ml-4 mr-4" type="search" name="search" placeholder="Search 1, Search 2, Search 3" aria-label="Search">
            <input type="hidden" name="page" value="1">
          </form>
        </li>
        <li class="nav-item" style="background:none !important">
          <a class="nav-link active" href="{% url 'photo:about' %}" style="background:none !important">About</a>
        </li>
        <li class="nav-item dropdown" style="background:none !important">
          <a class="nav-link active dropdown-toggle mr-3" style="background:none !important" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hi <span style="color: #ffc107;">{{ user.first_name }}</span>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'photo:list' %}?favorites={{ user.first_name }} {{ user.last_name }}&page=1">Favorites</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:member_list' %}">Members</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>